FROM nginx:latest
# COPY ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

# COPY ./etc/nginx/keys/server.key /etc/nginx/server.key
# COPY ./etc/nginx/keys/server.crt /etc/nginx/server.crt

# RUN chmod 400 /etc/nginx/server.key
